project:
  type: website
  resources:
    - CNAME

website:
  title: "Cook Book"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: recipes.qmd
        text: Recipes
      - about.qmd
    right:
      - href: https://gagerowden.com
        text: GageRowden.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



